import {
  BRAT_TEMPLATE_KEY,
  LYRIC_TEMPLATE_KEY,
  QUOTE_TEMPLATE_KEY,
  type StyleParams,
} from "./schema";

export interface StyleLabPreset {
  templateKey: string;
  family: "lyric" | "quote";
  name: string;
  tags: string[];
  params: StyleParams; // partial — gaps filled from schema defaults
}

// The starter library. Used by scripts/seed_style_lab.ts AND lazily by the
// style-lab service so every environment self-seeds without a manual run.
export const STYLE_LAB_PRESETS: StyleLabPreset[] = [
  // ── Lyric family ──────────────────────────────────────────────────────────
  // ── Brat family (dedicated brat-lyrics comp: accumulating words, auto-fit
  //    justified type, lo-fi pixelation) ─────────────────────────────────────
  {
    templateKey: BRAT_TEMPLATE_KEY,
    family: "lyric",
    name: "Brat",
    tags: ["preset", "brat"],
    params: {
      bgColor: "#8ACE00",
      textColor: "#000000",
      fontFamily: "Inter",
      fontWeight: 500,
      textTransform: "lowercase",
      lofiFactor: 5,
      maxFontSize: 120,
    },
  },
  {
    templateKey: LYRIC_TEMPLATE_KEY,
    family: "lyric",
    name: "Spotify Card",
    tags: ["preset", "karaoke"],
    params: {
      fontFamily: "Inter",
      fontWeight: 700,
      fontSize: 40,
      textColor: "#FFFFFF",
      highlightColor: "#1DB954",
      bgColor: "#121212",
      shadow: true,
      shadowIntensity: 0.35,
      lineMode: "karaoke",
      linesVisible: 2,
      positionYPercent: 62,
      entryType: "fade",
      entryDurationMs: 250,
    },
  },
  {
    templateKey: LYRIC_TEMPLATE_KEY,
    family: "lyric",
    name: "Minimal Lyric",
    tags: ["preset", "minimal"],
    params: {
      fontFamily: "Public Sans",
      fontWeight: 400,
      fontSize: 30,
      letterSpacing: 2,
      textTransform: "lowercase",
      textColor: "#F4F4F5",
      highlightColor: "#F4F4F5",
      bgColor: "#09090B",
      shadow: false,
      lineMode: "line-by-line",
      linesVisible: 1,
      positionYPercent: 78,
      entryType: "fade",
      entryDurationMs: 600,
      easing: "ease-in-out",
    },
  },
  {
    templateKey: LYRIC_TEMPLATE_KEY,
    family: "lyric",
    name: "News Lower-Third",
    tags: ["preset", "news"],
    params: {
      fontFamily: "Oswald",
      fontWeight: 600,
      fontSize: 34,
      letterSpacing: 1,
      textTransform: "uppercase",
      textColor: "#FFFFFF",
      highlightColor: "#E11D48",
      bgColor: "#18181B",
      stripColor: "#000000",
      stripOpacity: 0.85,
      padding: 22,
      alignment: "left",
      marginX: 40,
      maxWidthPercent: 92,
      positionYPercent: 78,
      lineMode: "line-by-line",
      linesVisible: 1,
      entryType: "slide-up",
      entryDurationMs: 350,
    },
  },
  {
    templateKey: LYRIC_TEMPLATE_KEY,
    family: "lyric",
    name: "Subtitle Box",
    tags: ["preset", "subtitle"],
    params: {
      fontFamily: "Source Sans 3",
      fontWeight: 600,
      fontSize: 30,
      textColor: "#FFFFFF",
      highlightColor: "#FFE951",
      bgColor: "#18181B",
      stripColor: "#000000",
      stripOpacity: 0.65,
      padding: 14,
      positionYPercent: 85,
      lineMode: "line-by-line",
      linesVisible: 1,
      entryType: "none",
      exitType: "none",
    },
  },
  // ── Overlay variants (transparent bg, for compositing over footage) ────────
  {
    templateKey: BRAT_TEMPLATE_KEY,
    family: "lyric",
    name: "Brat Overlay",
    tags: ["preset", "brat", "overlay"],
    params: {
      bgColor: "transparent",
      textColor: "#FFFFFF",
      fontFamily: "Inter",
      fontWeight: 500,
      textTransform: "lowercase",
      lofiFactor: 5,
      maxFontSize: 120,
    },
  },
  // ── Quote family ──────────────────────────────────────────────────────────
  {
    templateKey: QUOTE_TEMPLATE_KEY,
    family: "quote",
    name: "Statement Card",
    tags: ["preset", "statement"],
    params: {
      fontFamily: "Archivo",
      fontWeight: 800,
      fontSize: 54,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      textColor: "#FAFAFA",
      highlightColor: "#E11D48",
      bgColor: "transparent",
      shadow: true,
      shadowIntensity: 0.5,
      entryType: "slide-up",
      entryDurationMs: 500,
      easing: "spring",
    },
  },
  {
    templateKey: QUOTE_TEMPLATE_KEY,
    family: "quote",
    name: "Minimal Quote",
    tags: ["preset", "minimal"],
    params: {
      fontFamily: "Libre Franklin",
      fontWeight: 400,
      fontSize: 36,
      lineHeight: 1.5,
      textColor: "#E4E4E7",
      highlightColor: "#A1A1AA",
      bgColor: "transparent",
      shadow: false,
      maxWidthPercent: 76,
      entryType: "fade",
      entryDurationMs: 800,
      easing: "ease-in-out",
    },
  },
  {
    templateKey: QUOTE_TEMPLATE_KEY,
    family: "quote",
    name: "Statement Overlay",
    tags: ["preset", "statement", "overlay"],
    params: {
      fontFamily: "Archivo",
      fontWeight: 800,
      fontSize: 54,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      textColor: "#FAFAFA",
      highlightColor: "#E11D48",
      bgColor: "transparent",
      stripColor: "#000000",
      stripOpacity: 0.55,
      padding: 28,
      shadow: true,
      shadowIntensity: 0.5,
      positionYPercent: 78,
      entryType: "slide-up",
      entryDurationMs: 500,
      easing: "spring",
    },
  },
];
