import prisma from "@/lib/db";
import { getMultiplierDriveClient } from "@/app/api/managed/multiplier/google/drive-helper";
import { GoogleGenAI } from "@google/genai";
import crypto from "crypto";
import { bundle } from "@remotion/bundler";
import { renderStill, selectComposition } from "@remotion/renderer";
import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";

// Directory constants
const UPLOADS_DIR = path.join(process.cwd(), "public", "uploads", "multiplier");
const VARIATIONS_DIR = path.join(UPLOADS_DIR, "variations");
const STILLS_DIR = path.join(UPLOADS_DIR, "stills");
const OUTPUTS_DIR = path.join(UPLOADS_DIR, "outputs");

function ensureDirsExist() {
  [VARIATIONS_DIR, STILLS_DIR, OUTPUTS_DIR].forEach((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
}

// ─── Service Functions ────────────────────────────────────────────────────────

export async function createGroup(data: {
  name: string;
  campaignId: string;
  styleId: string;
  mappingMode?: "each" | "distribute";
  settings?: any;
  createdBy?: string;
}) {
  ensureDirsExist();
  return prisma.multiplierGroup.create({
    data: {
      name: data.name,
      campaignId: data.campaignId,
      styleId: data.styleId,
      mappingMode: data.mappingMode || "each",
      settings: data.settings || {},
      createdBy: data.createdBy,
    },
  });
}

export async function addVariation(groupId: string, tempFilePath: string, originalFileName: string) {
  ensureDirsExist();
  const ext = path.extname(originalFileName) || ".mp4";
  const id = crypto.randomUUID();
  const targetFileName = `var_${id}${ext}`;
  const targetPath = path.join(VARIATIONS_DIR, targetFileName);

  fs.copyFileSync(tempFilePath, targetPath);
  fs.unlinkSync(tempFilePath);

  const relativeRef = `/uploads/multiplier/variations/${targetFileName}`;

  // Find next order
  const count = await prisma.multiplierGroupVariation.count({ where: { groupId } });

  return prisma.multiplierGroupVariation.create({
    data: {
      groupId,
      videoRef: relativeRef,
      order: count,
    },
  });
}

export async function transcribeGroup(groupId: string): Promise<string> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: { variations: { orderBy: { order: "asc" } } },
  });

  if (!group) throw new Error("Group not found");
  if (group.variations.length === 0) throw new Error("No video variations found on this group");

  // Get the first variation to run alignment
  const variation = group.variations[0];
  const videoLocalPath = path.join(process.cwd(), "public", variation.videoRef);

  if (!fs.existsSync(videoLocalPath)) {
    throw new Error(`Video file does not exist on disk: ${variation.videoRef}`);
  }

  // Update status to TRANSCRIBING
  await prisma.multiplierGroup.update({
    where: { id: groupId },
    data: { transcriptStatus: "TRANSCRIBING" },
  });

  const tempJsonPath = path.join(os.tmpdir(), `transcription_${groupId}.json`);

  const cmd = [
    `./venv/bin/python3 "scripts/lyrical_composer.py"`,
    `-i "${videoLocalPath}"`,
    `-o "/dev/null"`,
    `--save-json "${tempJsonPath}"`,
    `--model "base"`,
    `--device "cpu"`,
  ].join(" ");

  console.log(`[Multiplier Transcribe] Running command: ${cmd}`);

  return new Promise<string>((resolve, reject) => {
    const { exec } = require("child_process");
    exec(
      cmd,
      {
        maxBuffer: 1024 * 1024 * 50,
        timeout: 300000,
        env: { ...process.env, HF_HOME: process.env.HF_HOME || "/home/nextjs/.cache/huggingface" },
      },
      async (error: any, stdout: string, stderr: string) => {
        if (error) {
          console.error("[Multiplier Transcribe] stable-ts execution failed:", stderr);
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: { transcriptStatus: "FAILED", errorMessage: `Transcription failed: ${error.message}` },
          });
          return reject(error);
        }

        if (!fs.existsSync(tempJsonPath)) {
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: { transcriptStatus: "FAILED", errorMessage: "Transcription JSON file was not generated by worker" },
          });
          return reject(new Error("Transcription JSON file not found"));
        }

        try {
          const jsonContent = fs.readFileSync(tempJsonPath, "utf-8");
          const wordList = JSON.parse(jsonContent);

          // Cleanup temp file
          try {
            fs.unlinkSync(tempJsonPath);
          } catch {}

          // Save transcript as JSON string on group
          const transcriptStr = JSON.stringify(wordList);
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: {
              transcript: transcriptStr,
              transcriptStatus: "TRANSCRIBED",
              errorMessage: null,
            },
          });

          resolve(transcriptStr);
        } catch (err: any) {
          reject(err);
        }
      }
    );
  });
}

export async function generateHooks(groupId: string, count: number, useCampaignContext: boolean): Promise<string[]> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: { campaign: true },
  });

  if (!group) throw new Error("Group not found");
  if (!group.transcript) throw new Error("Group has not been transcribed yet. Run transcription first.");

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY environment variable is missing");

  // Format transcript into raw readable text
  let rawText = "";
  try {
    const wordList = JSON.parse(group.transcript);
    if (Array.isArray(wordList)) {
      rawText = wordList.map((w: any) => w.text || "").join(" ");
    } else {
      rawText = String(group.transcript);
    }
  } catch {
    rawText = group.transcript;
  }

  let campaignContextPrompt = "";
  if (useCampaignContext && group.campaign) {
    campaignContextPrompt = `
CAMPAIGN CONTEXT:
Campaign Title: ${group.campaign.title}
Type: ${group.campaign.type}
Description: ${group.campaign.description}
Brief: ${group.campaign.brief}
Info messaging context: ${group.campaign.infoContent || "None"}
`;
  }

  const systemInstruction = `You are an editorial and political video caption writing assistant.
Your goal is to generate short, factual, and high-impact headlines or summaries based on the video transcript.
The output MUST look like standard breaking-news bars or credible journalistic cards, NOT casual entertainment.
Do NOT use emojis, clickbait questions, or hashtags. Keep the phrasing brief, serious, and informative.`;

  const prompt = `
Generate exactly ${count} unique video captions or hook headlines summarizing this video transcript.
${campaignContextPrompt}
VIDEO TRANSCRIPT:
"${rawText}"

Format your response strictly as a JSON array of strings, like this:
["First hook headline", "Second hook headline", "Third hook headline"]
Do not add any other markdown wrapper like \`\`\`json or text blocks. Generate only the raw JSON array.`;

  const ai = new GoogleGenAI({ apiKey });
  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash",
    contents: prompt,
    config: {
      systemInstruction,
    },
  });

  const responseText = response.text || "";
  console.log("[Multiplier Gemini Response]:", responseText);

  try {
    // Strip code block markers if Gemini included them
    let cleaned = responseText.trim();
    if (cleaned.startsWith("```")) {
      cleaned = cleaned.replace(/^```json\s*/, "").replace(/^```\s*/, "").replace(/\s*```$/, "");
    }
    const hooks = JSON.parse(cleaned);
    if (Array.isArray(hooks)) {
      // Save hooks to DB
      await prisma.multiplierHook.deleteMany({ where: { groupId } });
      for (let i = 0; i < hooks.length; i++) {
        await prisma.multiplierHook.create({
          data: {
            groupId,
            text: hooks[i].trim(),
            source: "ai",
            order: i,
          },
        });
      }
      return hooks;
    }
  } catch (parseErr) {
    console.error("[Multiplier Gemini Parse Error]:", parseErr, responseText);
  }

  // Fallback line splits if JSON parse failed
  const lines = responseText
    .split(/\r?\n/)
    .map((l) => l.trim().replace(/^-\s*/, "").replace(/^"\s*/, "").replace(/\s*"$/, ""))
    .filter((l) => l.length > 3 && !l.startsWith("[") && !l.startsWith("]"));

  if (lines.length > 0) {
    await prisma.multiplierHook.deleteMany({ where: { groupId } });
    const saved = lines.slice(0, count);
    for (let i = 0; i < saved.length; i++) {
      await prisma.multiplierHook.create({
        data: {
          groupId,
          text: saved[i],
          source: "ai",
          order: i,
        },
      });
    }
    return saved;
  }

  throw new Error("Failed to parse Gemini generated hooks. Please check format or retry.");
}

export async function addManualHook(groupId: string, text: string) {
  const count = await prisma.multiplierHook.count({ where: { groupId } });
  return prisma.multiplierHook.create({
    data: {
      groupId,
      text: text.trim(),
      source: "manual",
      order: count,
    },
  });
}

export async function updateHook(hookId: string, text: string) {
  return prisma.multiplierHook.update({
    where: { id: hookId },
    data: { text: text.trim() },
  });
}

export async function previewOutputCount(groupId: string): Promise<number> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: {
      _count: {
        select: { variations: true, hooks: true },
      },
    },
  });
  if (!group) return 0;
  const vCount = group._count.variations;
  const hCount = group._count.hooks;

  if (group.mappingMode === "distribute") {
    return hCount; // each hook used exactly once
  }
  return vCount * hCount; // each hook on each variation
}

// Global cached bundle location for Remotion
let cachedBundleLocation: string | null = null;
async function getRemotionBundle() {
  if (cachedBundleLocation && fs.existsSync(cachedBundleLocation)) {
    return cachedBundleLocation;
  }
  const entryPoint = path.join(process.cwd(), "src", "remotion", "index.ts");
  cachedBundleLocation = await bundle(entryPoint);
  return cachedBundleLocation;
}

export async function renderCaptionStill(
  styleId: string,
  hookText: string,
  settings: any,
  outputId: string
): Promise<string> {
  ensureDirsExist();
  const bundleLocation = await getRemotionBundle();

  // Merge presets default settings based on styleId
  const customProps = settings || {};
  const inputProps = {
    styleKey: styleId,
    text: hookText,
    fontSize: customProps.fontSize ?? 32,
    fontColor: customProps.fontColor ?? "#FFFFFF",
    bgStripColor: customProps.bgStripColor ?? "#000000",
    bgStripOpacity: customProps.bgStripOpacity ?? 0.85,
    positionYPercent: customProps.positionYPercent ?? 75,
    marginX: customProps.marginX ?? 40,
    paddingY: customProps.paddingY ?? 20,
    paddingX: customProps.paddingX ?? 20,
    accentColor: customProps.accentColor ?? "#E11D48",
    author: customProps.author || "",
  };

  const composition = await selectComposition({
    serveUrl: bundleLocation,
    id: "editorial-caption",
    inputProps,
  });

  const stillFileName = `still_${outputId}.png`;
  const stillPath = path.join(STILLS_DIR, stillFileName);

  await renderStill({
    composition,
    serveUrl: bundleLocation,
    output: stillPath,
    inputProps,
    browserExecutable: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
  });

  return stillPath;
}

export async function composeOutput(
  variationRef: string,
  stillPath: string,
  outputId: string,
  settings: any
): Promise<string> {
  ensureDirsExist();
  const inputVideoPath = path.join(process.cwd(), "public", variationRef);
  if (!fs.existsSync(inputVideoPath)) throw new Error(`Source video not found: ${variationRef}`);

  const outputFileName = `multi_${outputId}.mp4`;
  const localOutputPath = path.join(OUTPUTS_DIR, outputFileName);

  const hookDuration = settings?.hookDuration ?? 5;
  const animType = settings?.animationType ?? "NONE";
  const animDuration = settings?.animationDuration ?? 0.5;

  let filterComplex = "";
  if (animType === "FADE_IN" && animDuration > 0) {
    filterComplex = `[1:v]fade=in:st=0:d=${animDuration}:alpha=1[overlay_fade];[0:v][overlay_fade]overlay=x=0:y=0:enable='lt(t,${hookDuration})'[v]`;
  } else if (animType === "SLIDE_UP" && animDuration > 0) {
    // slides Y up from +60px to 0px
    filterComplex = `[0:v][1:v]overlay=x=0:y='if(lt(t,${animDuration}), 60*(1-t/${animDuration}), 0)':enable='lt(t,${hookDuration})'[v]`;
  } else {
    filterComplex = `[0:v][1:v]overlay=x=0:y=0:enable='lt(t,${hookDuration})'[v]`;
  }

  const ffmpegArgs = [
    "-y",
    "-i", inputVideoPath,
    "-i", stillPath,
    "-filter_complex", filterComplex,
    "-map", "[v]",
    "-map", "0:a?",
    "-c:v", "libx264",
    "-preset", "ultrafast",
    "-crf", "23",
    "-c:a", "aac",
    "-b:a", "192k",
    "-shortest",
    localOutputPath,
  ];

  return new Promise<string>((resolve, reject) => {
    const { spawn } = require("child_process");
    const proc = spawn("ffmpeg", ffmpegArgs);

    let stderr = "";
    proc.stderr.on("data", (data: any) => {
      stderr += data.toString();
    });

    proc.on("close", (code: number) => {
      if (code === 0) {
        resolve(`/uploads/multiplier/outputs/${outputFileName}`);
      } else {
        console.error("[Multiplier Composer FFmpeg error]:", stderr);
        reject(new Error(`FFmpeg processing failed with code ${code}. Stderr: ${stderr}`));
      }
    });
  });
}

// ─── Background Queue Rendering orchestrator ───────────────────────────────

let isQueueProcessing = false;

export async function triggerQueueWorker() {
  if (isQueueProcessing) return;
  isQueueProcessing = true;
  processRenderQueue().finally(() => {
    isQueueProcessing = false;
  });
}

async function processRenderQueue() {
  console.log("[Multiplier Worker] Starting processing render queue...");

  while (true) {
    const output = await prisma.multiplierOutput.findFirst({
      where: { status: "PENDING" },
      include: {
        group: true,
        variation: true,
        hook: true,
      },
      orderBy: { createdAt: "asc" },
    });

    if (!output) {
      console.log("[Multiplier Worker] Queue empty. Going to sleep.");
      break;
    }

    // Update state to RENDERING
    await prisma.multiplierOutput.update({
      where: { id: output.id },
      data: { status: "RENDERING" },
    });

    // Update parent group status to RENDERING
    await prisma.multiplierGroup.update({
      where: { id: output.groupId },
      data: { status: "RENDERING" },
    });

    let stillPath = "";
    try {
      const settings = typeof output.group.settings === "string" 
        ? JSON.parse(output.group.settings) 
        : (output.group.settings || {});

      // 1. Render transparent PNG still in Remotion
      console.log(`[Multiplier Worker] Rendering still for Hook: "${output.hook.text.substring(0, 30)}..."`);
      stillPath = await renderCaptionStill(output.group.styleId, output.hook.text, settings, output.id);

      // 2. Composite variation with still overlay in FFmpeg
      console.log(`[Multiplier Worker] Compositing still on video: ${output.variation.videoRef}`);
      const relativeVideoUrl = await composeOutput(output.variation.videoRef, stillPath, output.id, settings);

      // Delete the still PNG after success
      try {
        fs.unlinkSync(stillPath);
      } catch {}

      // 3. Auto-upload to Google Drive if connected
      let driveFolderId: string | null = null;
      try {
        const drive = await getMultiplierDriveClient();
        const targetFolder = output.group.campaignId // can fall back to campaign default folders or group settings
          ? (await prisma.campaign.findUnique({ where: { id: output.group.campaignId } }))?.coverImageUrl // placeholder checks
          : null;

        const mainDriveFolder = settings?.driveFolderId || null;
        const finalFolderId = output.driveFolderId || mainDriveFolder;

        if (drive && finalFolderId) {
          const localFilePath = path.join(process.cwd(), "public", relativeVideoUrl);
          const cleanHookSlug = output.hook.text.replace(/[^a-zA-Z0-9 ]/g, "").trim().replace(/\s+/g, "_").substring(0, 40);
          const fileName = `multi_${output.id}_${cleanHookSlug}.mp4`;

          console.log(`[Multiplier Worker] Uploading output ${output.id} to Drive Folder ${finalFolderId}`);
          const fileStream = fs.createReadStream(localFilePath);
          await drive.files.create({
            requestBody: {
              name: fileName,
              parents: [finalFolderId],
            },
            media: {
              mimeType: "video/mp4",
              body: fileStream,
            },
            fields: "id",
            supportsAllDrives: true,
          });
          driveFolderId = finalFolderId;
        }
      } catch (driveErr: any) {
        console.error(`[Multiplier Worker] Drive upload failed for output ${output.id}:`, driveErr?.message || driveErr);
      }

      // Update output row
      await prisma.multiplierOutput.update({
        where: { id: output.id },
        data: {
          status: "COMPLETED",
          outputRef: relativeVideoUrl,
          driveFolderId,
          errorMessage: null,
        },
      });

      // Update group overall status check
      await updateParentGroupStatus(output.groupId);

    } catch (err: any) {
      console.error(`[Multiplier Worker] Output ${output.id} failed:`, err);
      // Clean still path if stuck on disk
      if (stillPath && fs.existsSync(stillPath)) {
        try { fs.unlinkSync(stillPath); } catch {}
      }

      await prisma.multiplierOutput.update({
        where: { id: output.id },
        data: {
          status: "FAILED",
          errorMessage: err.message || String(err),
        },
      });

      await updateParentGroupStatus(output.groupId);
    }
  }
}

async function updateParentGroupStatus(groupId: string) {
  const allOutputs = await prisma.multiplierOutput.findMany({
    where: { groupId },
    select: { status: true },
  });

  const allDone = allOutputs.every((o: any) => o.status === "COMPLETED" || o.status === "FAILED");
  if (allDone) {
    const hasFailed = allOutputs.some((o: any) => o.status === "FAILED");
    await prisma.multiplierGroup.update({
      where: { id: groupId },
      data: {
        status: hasFailed ? "FAILED" : "COMPLETED",
      },
    });
  }
}

export async function startGroupRender(groupId: string) {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: {
      variations: { orderBy: { order: "asc" } },
      hooks: { orderBy: { order: "asc" } },
    },
  });

  if (!group) throw new Error("Group not found");
  if (group.variations.length === 0) throw new Error("Add at least one video variation to render");
  if (group.hooks.length === 0) throw new Error("Add at least one hook to render");

  // Delete previous outputs
  await prisma.multiplierOutput.deleteMany({ where: { groupId } });

  // Map outputs
  if (group.mappingMode === "distribute") {
    // round-robin hooks across variations
    for (let i = 0; i < group.hooks.length; i++) {
      const hook = group.hooks[i];
      const variation = group.variations[i % group.variations.length];

      await prisma.multiplierOutput.create({
        data: {
          groupId,
          hookId: hook.id,
          variationId: variation.id,
          status: "PENDING",
        },
      });
    }
  } else {
    // each hook on each variation
    for (const hook of group.hooks) {
      for (const variation of group.variations) {
        await prisma.multiplierOutput.create({
          data: {
            groupId,
            hookId: hook.id,
            variationId: variation.id,
            status: "PENDING",
          },
        });
      }
    }
  }

  // Update status to QUEUED
  await prisma.multiplierGroup.update({
    where: { id: groupId },
    data: { status: "QUEUED", errorMessage: null },
  });

  // Run worker background loop
  triggerQueueWorker();

  return true;
}

export async function retryOutput(outputId: string) {
  const output = await prisma.multiplierOutput.update({
    where: { id: outputId },
    data: { status: "PENDING", errorMessage: null },
  });

  await prisma.multiplierGroup.update({
    where: { id: output.groupId },
    data: { status: "QUEUED" },
  });

  triggerQueueWorker();

  return output;
}
