import prisma from "@/lib/db";
import { getMultiplierDriveClient } from "@/app/api/managed/multiplier/google/drive-helper";
import { GoogleGenAI } from "@google/genai";
import crypto from "crypto";
import { spawn, exec } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";

// Directory constants
const UPLOADS_DIR = path.join(process.cwd(), "public", "uploads", "multiplier");
const VARIATIONS_DIR = path.join(UPLOADS_DIR, "variations");
const STILLS_DIR = path.join(UPLOADS_DIR, "stills");
const OUTPUTS_DIR = path.join(UPLOADS_DIR, "outputs");

function ensureDirsExist() {
  [VARIATIONS_DIR, STILLS_DIR, OUTPUTS_DIR].forEach((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
}

// ─── Service Functions ────────────────────────────────────────────────────────

export async function createGroup(data: {
  name: string;
  campaignId: string;
  styleId: string;
  mappingMode?: "each" | "distribute";
  settings?: any;
  createdBy?: string;
}) {
  ensureDirsExist();
  return prisma.multiplierGroup.create({
    data: {
      name: data.name,
      campaignId: data.campaignId,
      styleId: data.styleId,
      mappingMode: data.mappingMode || "each",
      settings: data.settings || {},
      createdBy: data.createdBy,
    },
  });
}

export async function addVariation(groupId: string, tempFilePath: string, originalFileName: string) {
  ensureDirsExist();
  const ext = path.extname(originalFileName) || ".mp4";
  const id = crypto.randomUUID();
  const targetFileName = `var_${id}${ext}`;
  const targetPath = path.join(VARIATIONS_DIR, targetFileName);

  fs.copyFileSync(tempFilePath, targetPath);
  fs.unlinkSync(tempFilePath);

  const relativeRef = `/uploads/multiplier/variations/${targetFileName}`;

  // Find next order
  const count = await prisma.multiplierGroupVariation.count({ where: { groupId } });

  return prisma.multiplierGroupVariation.create({
    data: {
      groupId,
      videoRef: relativeRef,
      order: count,
    },
  });
}

export async function transcribeGroup(groupId: string): Promise<string> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: { variations: { orderBy: { order: "asc" } } },
  });

  if (!group) throw new Error("Group not found");
  if (group.variations.length === 0) throw new Error("No video variations found on this group");

  // Get the first variation to run alignment
  const variation = group.variations[0];
  const videoLocalPath = path.join(process.cwd(), "public", variation.videoRef);

  if (!fs.existsSync(videoLocalPath)) {
    throw new Error(`Video file does not exist on disk: ${variation.videoRef}`);
  }

  // Update status to TRANSCRIBING
  await prisma.multiplierGroup.update({
    where: { id: groupId },
    data: { transcriptStatus: "TRANSCRIBING" },
  });

  const tempJsonPath = path.join(os.tmpdir(), `transcription_${groupId}.json`);

  const cmd = [
    `./venv/bin/python3 "scripts/lyrical_composer.py"`,
    `-i "${videoLocalPath}"`,
    `-o "/dev/null"`,
    `--save-json "${tempJsonPath}"`,
    `--model "tiny"`,
    `--device "cpu"`,
  ].join(" ");

  console.log(`[Multiplier Transcribe] Running command: ${cmd}`);

  return new Promise<string>((resolve, reject) => {
    const { exec } = require("child_process");
    exec(
      cmd,
      {
        maxBuffer: 1024 * 1024 * 50,
        timeout: 300000,
        env: { ...process.env, HF_HOME: process.env.HF_HOME || "/home/nextjs/.cache/huggingface" },
      },
      async (error: any, stdout: string, stderr: string) => {
        if (error) {
          console.error("[Multiplier Transcribe] stable-ts execution failed:", stderr);
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: { transcriptStatus: "FAILED", errorMessage: `Transcription failed: ${error.message}` },
          });
          return reject(error);
        }

        if (!fs.existsSync(tempJsonPath)) {
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: { transcriptStatus: "FAILED", errorMessage: "Transcription JSON file was not generated by worker" },
          });
          return reject(new Error("Transcription JSON file not found"));
        }

        try {
          const jsonContent = fs.readFileSync(tempJsonPath, "utf-8");
          const wordList = JSON.parse(jsonContent);

          // Cleanup temp file
          try {
            fs.unlinkSync(tempJsonPath);
          } catch {}

          // Save transcript as JSON string on group
          const transcriptStr = JSON.stringify(wordList);
          await prisma.multiplierGroup.update({
            where: { id: groupId },
            data: {
              transcript: transcriptStr,
              transcriptStatus: "TRANSCRIBED",
              errorMessage: null,
            },
          });

          resolve(transcriptStr);
        } catch (err: any) {
          reject(err);
        }
      }
    );
  });
}

type GroupWithCampaign = {
  transcript: string | null;
  campaign: {
    title: string;
    type: string;
    description: string;
    brief: string;
    infoContent: string | null;
  } | null;
};

// Shared Gemini pipeline: builds the prompt, calls the model, parses hook texts.
async function generateHookTexts(group: GroupWithCampaign, count: number, useCampaignContext: boolean, customPrompt?: string): Promise<string[]> {
  if (!group.transcript) throw new Error("Group has not been transcribed yet. Run transcription first.");

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY environment variable is missing");

  // Format transcript into raw readable text
  let rawText = "";
  try {
    const wordList = JSON.parse(group.transcript);
    if (Array.isArray(wordList)) {
      rawText = wordList.map((w: any) => w.word || w.text || "").join(" ");
    } else {
      rawText = String(group.transcript);
    }
  } catch {
    rawText = group.transcript;
  }

  let campaignContextPrompt = "";
  if (useCampaignContext && group.campaign) {
    campaignContextPrompt = `
CAMPAIGN CONTEXT:
Campaign Title: ${group.campaign.title}
Type: ${group.campaign.type}
Description: ${group.campaign.description}
Brief: ${group.campaign.brief}
Info messaging context: ${group.campaign.infoContent || "None"}
`;
  }

  const systemInstruction = `You are an editorial and political video caption writing assistant.
Your goal is to generate short, factual, and high-impact headlines or summaries based on the video transcript.
The output MUST look like standard breaking-news bars or credible journalistic cards, NOT casual entertainment.
Do NOT use emojis, clickbait questions, or hashtags. Keep the phrasing brief, serious, and informative.`;

  let prompt = customPrompt;
  if (!prompt) {
    prompt = `
Generate exactly ${count} unique video captions or hook headlines summarizing this video transcript.
${campaignContextPrompt}
VIDEO TRANSCRIPT:
"${rawText}"

Format your response strictly as a JSON array of strings, like this:
["First hook headline", "Second hook headline", "Third hook headline"]
Do not add any other markdown wrapper like \`\`\`json or text blocks. Generate only the raw JSON array.`;
  } else {
    // Sync hooks count in custom prompt if specified
    prompt = prompt.replace(/Generate exactly \d+/i, `Generate exactly ${count}`);
    // Always append strict JSON format instructions if not present to ensure parseability
    if (!prompt.includes("Format your response strictly as a JSON array of strings")) {
      prompt += `\n\nFormat your response strictly as a JSON array of strings, like this:\n["First hook headline", "Second hook headline", "Third hook headline"]\nDo not add any other markdown wrapper like \`\`\`json or text blocks. Generate only the raw JSON array.`;
    }
  }

  const ai = new GoogleGenAI({ apiKey });
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      systemInstruction,
    },
  });

  const responseText = response.text || "";
  console.log("[Multiplier Gemini Response]:", responseText);

  try {
    // Strip code block markers if Gemini included them
    let cleaned = responseText.trim();
    if (cleaned.startsWith("```")) {
      cleaned = cleaned.replace(/^```json\s*/, "").replace(/^```\s*/, "").replace(/\s*```$/, "");
    }
    const hooks = JSON.parse(cleaned);
    if (Array.isArray(hooks)) {
      return hooks.map((h: any) => String(h).trim()).filter((h: string) => h.length > 0);
    }
  } catch (parseErr) {
    console.error("[Multiplier Gemini Parse Error]:", parseErr, responseText);
  }

  // Fallback line splits if JSON parse failed
  const lines = responseText
    .split(/\r?\n/)
    .map((l) => l.trim().replace(/^-\s*/, "").replace(/^"\s*/, "").replace(/\s*"$/, ""))
    .filter((l) => l.length > 3 && !l.startsWith("[") && !l.startsWith("]"));

  if (lines.length > 0) {
    return lines.slice(0, count);
  }

  throw new Error("Failed to parse Gemini generated hooks. Please check format or retry.");
}

export async function generateHooks(groupId: string, count: number, useCampaignContext: boolean, customPrompt?: string): Promise<string[]> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: { campaign: true },
  });

  if (!group) throw new Error("Group not found");
  if (!group.transcript) throw new Error("Group has not been transcribed yet. Run transcription first.");

  const hooks = await generateHookTexts(group, count, useCampaignContext, customPrompt);

  // Replace the group's hook list with the generated set
  await prisma.multiplierHook.deleteMany({ where: { groupId } });
  for (let i = 0; i < hooks.length; i++) {
    await prisma.multiplierHook.create({
      data: {
        groupId,
        text: hooks[i].trim(),
        source: "ai",
        order: i,
      },
    });
  }

  return hooks;
}

// Regenerates the text of a single existing hook using the same Gemini pipeline.
export async function regenerateHook(hookId: string) {
  const hook = await prisma.multiplierHook.findUnique({
    where: { id: hookId },
  });
  if (!hook) throw new Error("Hook not found");

  const group = await prisma.multiplierGroup.findUnique({
    where: { id: hook.groupId },
    include: { campaign: true },
  });
  if (!group) throw new Error("Group not found");
  if (!group.transcript) throw new Error("Group has not been transcribed yet. Run transcription first.");

  const texts = await generateHookTexts(group, 1, !!group.campaignId);
  const newText = (texts[0] || "").trim();
  if (!newText) throw new Error("Gemini returned an empty hook. Please retry.");

  return prisma.multiplierHook.update({
    where: { id: hookId },
    data: { text: newText, source: "ai" },
  });
}

export async function addManualHook(groupId: string, text: string) {
  const count = await prisma.multiplierHook.count({ where: { groupId } });
  return prisma.multiplierHook.create({
    data: {
      groupId,
      text: text.trim(),
      source: "manual",
      order: count,
    },
  });
}

export async function updateHook(hookId: string, text: string) {
  return prisma.multiplierHook.update({
    where: { id: hookId },
    data: { text: text.trim() },
  });
}

export async function previewOutputCount(groupId: string): Promise<number> {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: {
      _count: {
        select: { variations: true, hooks: true },
      },
    },
  });
  if (!group) return 0;
  const vCount = group._count.variations;
  const hCount = group._count.hooks;

  if (group.mappingMode === "distribute") {
    return hCount; // each hook used exactly once
  }
  return vCount * hCount; // each hook on each variation
}

export async function renderCaptionStill(
  styleId: string,
  hookText: string,
  settings: any,
  outputId: string
): Promise<string> {
  ensureDirsExist();
  const stillFileName = `still_${outputId}.png`;
  const stillPath = path.join(STILLS_DIR, stillFileName);

  let finalStyleId = styleId;
  let customProps = settings || {};

  // If styleId is a SavedStyle UUID, resolve it
  if (styleId.length > 20) {
    const savedStyle = await prisma.savedStyle.findUnique({
      where: { id: styleId }
    });
    if (savedStyle) {
      finalStyleId = savedStyle.templateKey;
      let savedParams: any = savedStyle.params;
      if (typeof savedParams === "string") {
        try {
          savedParams = JSON.parse(savedParams);
          if (typeof savedParams === "string") {
            savedParams = JSON.parse(savedParams);
          }
        } catch {
          savedParams = {};
        }
      }
      if (!savedParams) savedParams = {};
      customProps = {
        ...customProps,
        ...savedParams
      };
    }
  }

  // Merge presets default settings based on finalStyleId
  const fontSize = customProps.fontSize ?? 32;
  const fontColor = customProps.fontColor ?? customProps.textColor ?? "#FFFFFF";
  const bgStripColor = customProps.bgStripColor ?? customProps.bgColor ?? "#000000";
  const bgStripOpacity = customProps.bgStripOpacity ?? customProps.bgOpacity ?? 0.85;
  const positionYPercent = customProps.positionYPercent ?? customProps.positionY ?? 75;
  const accentColor = customProps.accentColor ?? "#E11D48";
  const author = customProps.author || "";

  const pythonExecutable = fs.existsSync(path.join(process.cwd(), "venv", "bin", "python3"))
    ? "./venv/bin/python3"
    : "python3";

  const fontFamily = customProps.fontFamily || "";

  const pythonArgs = [
    "scripts/generate_still.py",
    "--text", hookText,
    "--font-size", String(fontSize),
    "--font-color", fontColor,
    "--bg-color", bgStripColor,
    "--bg-opacity", String(bgStripOpacity),
    "--position-y", String(positionYPercent),
    "--style", finalStyleId,
    "--accent-color", accentColor,
    "--author", author,
    "--font-family", fontFamily,
    "--output", stillPath,
  ];

  return new Promise<string>((resolve, reject) => {
    const { spawn } = require("child_process");
    const proc = spawn(pythonExecutable, pythonArgs);

    let stderr = "";
    proc.stderr.on("data", (data: any) => {
      stderr += data.toString();
    });

    proc.on("close", (code: number) => {
      if (code === 0 && fs.existsSync(stillPath)) {
        resolve(stillPath);
      } else {
        reject(new Error(`Pillow generating overlay failed with code ${code}. Stderr: ${stderr}`));
      }
    });
  });
}

export async function composeOutput(
  variationRef: string,
  stillPath: string,
  outputId: string,
  settings: any
): Promise<string> {
  ensureDirsExist();
  const inputVideoPath = path.join(process.cwd(), "public", variationRef);
  if (!fs.existsSync(inputVideoPath)) throw new Error(`Source video not found: ${variationRef}`);

  const outputFileName = `multi_${outputId}.mp4`;
  const localOutputPath = path.join(OUTPUTS_DIR, outputFileName);

  const hookDuration = settings?.hookDuration ?? 5;
  const animType = settings?.animationType ?? "NONE";
  const animDuration = settings?.animationDuration ?? 0.5;

  // Normalize the canvas to 720x1280 BEFORE overlay: the still is rendered at
  // 720x1280, and encoding a 1080p source is ~2.25x the pixels for no benefit
  // (TikTok re-compresses above ~5-10 Mbps anyway).
  const canvasFilter = `scale='if(gte(iw/ih,720/1280),-1,720)':'if(gte(iw/ih,720/1280),1280,-1)',crop=720:1280`;

  let filterComplex = "";
  if (animType === "FADE_IN" && animDuration > 0) {
    filterComplex = `[0:v]${canvasFilter}[bg];[1:v]fade=in:st=0:d=${animDuration}:alpha=1[overlay_fade];[bg][overlay_fade]overlay=x=0:y=0:enable='lt(t,${hookDuration})'[v]`;
  } else if (animType === "SLIDE_UP" && animDuration > 0) {
    // slides Y up from +60px to 0px
    filterComplex = `[0:v]${canvasFilter}[bg];[bg][1:v]overlay=x=0:y='if(lt(t,${animDuration}), 60*(1-t/${animDuration}), 0)':enable='lt(t,${hookDuration})'[v]`;
  } else {
    filterComplex = `[0:v]${canvasFilter}[bg];[bg][1:v]overlay=x=0:y=0:enable='lt(t,${hookDuration})'[v]`;
  }

  const ffmpegArgs = [
    "-y",
    "-i", inputVideoPath,
    "-i", stillPath,
    "-filter_complex", filterComplex,
    "-map", "[v]",
    "-map", "0:a?",
    "-c:v", "libx264",
    // veryfast ~3-5x faster than medium on the shared CPU; the 8M maxrate cap
    // keeps file sizes bounded, so the tradeoff is only a slight efficiency loss.
    "-preset", "veryfast",
    "-crf", "26",
    "-maxrate", "8M",
    "-bufsize", "16M",
    "-r", "30",
    "-pix_fmt", "yuv420p",
    "-c:a", "aac",
    "-b:a", "128k",
    "-movflags", "+faststart",
    "-shortest",
    localOutputPath,
  ];

  return new Promise<string>((resolve, reject) => {
    const { spawn } = require("child_process");
    const proc = spawn("ffmpeg", ffmpegArgs);

    let stderr = "";
    proc.stderr.on("data", (data: any) => {
      stderr += data.toString();
    });

    proc.on("close", (code: number) => {
      if (code === 0) {
        resolve(`/uploads/multiplier/outputs/${outputFileName}`);
      } else {
        console.error("[Multiplier Composer FFmpeg error]:", stderr);
        reject(new Error(`FFmpeg processing failed with code ${code}. Stderr: ${stderr}`));
      }
    });
  });
}

// ─── Background Queue Rendering orchestrator ───────────────────────────────

let isQueueProcessing = false;
let isRenderPaused = false;

export function getRenderQueueState() {
  return { paused: isRenderPaused, processing: isQueueProcessing };
}

// Outputs left in RENDERING by a crash/restart are never picked up again
// (the loop only fetches PENDING) — reset them so the queue can move.
export async function recoverStaleRenderingOutputs(staleMinutes = 2): Promise<number> {
  const staleBefore = new Date(Date.now() - staleMinutes * 60 * 1000);
  const reset = await prisma.multiplierOutput.updateMany({
    where: { status: "RENDERING", updatedAt: { lt: staleBefore } },
    data: { status: "PENDING" },
  });
  if (reset.count > 0) {
    console.log(`[Multiplier Worker] Recovered ${reset.count} output(s) stuck in RENDERING`);
  }
  return reset.count;
}

export async function pauseRenderQueue() {
  isRenderPaused = true;
  return getRenderQueueState();
}

export async function resumeRenderQueue() {
  isRenderPaused = false;
  await recoverStaleRenderingOutputs();
  triggerQueueWorker();
  return getRenderQueueState();
}

export async function triggerQueueWorker() {
  if (isQueueProcessing || isRenderPaused) return;
  isQueueProcessing = true;
  processRenderQueue().finally(() => {
    isQueueProcessing = false;
  });
}

async function processRenderQueue() {
  console.log("[Multiplier Worker] Starting processing render queue...");

  // A previous process may have died mid-render — recover before starting.
  await recoverStaleRenderingOutputs().catch((err) => {
    console.error("[Multiplier Worker] Stale-output recovery failed:", err);
  });

  while (true) {
    if (isRenderPaused) {
      console.log("[Multiplier Worker] Paused by operator. Stopping loop.");
      break;
    }

    const output = await prisma.multiplierOutput.findFirst({
      where: { status: "PENDING" },
      include: {
        group: true,
        variation: true,
        hook: true,
      },
      orderBy: { createdAt: "asc" },
    });

    if (!output) {
      console.log("[Multiplier Worker] Queue empty. Going to sleep.");
      break;
    }

    // Update state to RENDERING
    await prisma.multiplierOutput.update({
      where: { id: output.id },
      data: { status: "RENDERING" },
    });

    // Update parent group status to RENDERING
    await prisma.multiplierGroup.update({
      where: { id: output.groupId },
      data: { status: "RENDERING" },
    });

    let stillPath = "";
    try {
      const settings = typeof output.group.settings === "string" 
        ? JSON.parse(output.group.settings) 
        : (output.group.settings || {});

      // 1. Render transparent PNG still in Remotion
      console.log(`[Multiplier Worker] Rendering still for Hook: "${output.hook.text.substring(0, 30)}..."`);
      stillPath = await renderCaptionStill(output.group.styleId, output.hook.text, settings, output.id);

      // 2. Composite variation with still overlay in FFmpeg
      console.log(`[Multiplier Worker] Compositing still on video: ${output.variation.videoRef}`);
      const relativeVideoUrl = await composeOutput(output.variation.videoRef, stillPath, output.id, settings);

      // Delete the still PNG after success
      try {
        fs.unlinkSync(stillPath);
      } catch {}

      // 3. Auto-upload to Google Drive if connected
      let driveFolderId: string | null = null;
      try {
        const drive = await getMultiplierDriveClient();
        const targetFolder = output.group.campaignId // can fall back to campaign default folders or group settings
          ? (await prisma.campaign.findUnique({ where: { id: output.group.campaignId } }))?.coverImageUrl // placeholder checks
          : null;

        const mainDriveFolder = settings?.driveFolderId || null;
        const finalFolderId = output.driveFolderId || mainDriveFolder;

        if (drive && finalFolderId) {
          const localFilePath = path.join(process.cwd(), "public", relativeVideoUrl);
          const cleanHookSlug = output.hook.text.replace(/[^a-zA-Z0-9 ]/g, "").trim().replace(/\s+/g, "_").substring(0, 40);
          const fileName = `multi_${output.id}_${cleanHookSlug}.mp4`;

          console.log(`[Multiplier Worker] Uploading output ${output.id} to Drive Folder ${finalFolderId}`);
          const fileStream = fs.createReadStream(localFilePath);
          await drive.files.create({
            requestBody: {
              name: fileName,
              parents: [finalFolderId],
            },
            media: {
              mimeType: "video/mp4",
              body: fileStream,
            },
            fields: "id",
            supportsAllDrives: true,
          });
          driveFolderId = finalFolderId;
        }
      } catch (driveErr: any) {
        console.error(`[Multiplier Worker] Drive upload failed for output ${output.id}:`, driveErr?.message || driveErr);
      }

      // Update output row
      await prisma.multiplierOutput.update({
        where: { id: output.id },
        data: {
          status: "COMPLETED",
          outputRef: relativeVideoUrl,
          driveFolderId,
          errorMessage: null,
        },
      });

      // Update group overall status check
      await updateParentGroupStatus(output.groupId);

    } catch (err: any) {
      console.error(`[Multiplier Worker] Output ${output.id} failed:`, err);
      // Clean still path if stuck on disk
      if (stillPath && fs.existsSync(stillPath)) {
        try { fs.unlinkSync(stillPath); } catch {}
      }

      await prisma.multiplierOutput.update({
        where: { id: output.id },
        data: {
          status: "FAILED",
          errorMessage: err.message || String(err),
        },
      });

      await updateParentGroupStatus(output.groupId);
    }
  }

  // Sweep: groups stuck in QUEUED/RENDERING whose outputs are all terminal
  // (e.g. after a restart or a pause) get their correct final status.
  try {
    const stuckGroups = await prisma.multiplierGroup.findMany({
      where: { status: { in: ["QUEUED", "RENDERING"] } },
      include: { outputs: { select: { status: true } } },
    });
    for (const g of stuckGroups) {
      const anyActive = g.outputs.some((o) => o.status === "PENDING" || o.status === "RENDERING");
      if (anyActive) continue;
      const hasFailed = g.outputs.some((o) => o.status === "FAILED");
      await prisma.multiplierGroup.update({
        where: { id: g.id },
        data: { status: hasFailed ? "FAILED" : "COMPLETED" },
      });
    }
  } catch (err) {
    console.error("[Multiplier Worker] Group status sweep failed:", err);
  }
}

async function updateParentGroupStatus(groupId: string) {
  const allOutputs = await prisma.multiplierOutput.findMany({
    where: { groupId },
    select: { status: true },
  });

  const allDone = allOutputs.every((o: any) => o.status === "COMPLETED" || o.status === "FAILED");
  if (allDone) {
    const hasFailed = allOutputs.some((o: any) => o.status === "FAILED");
    await prisma.multiplierGroup.update({
      where: { id: groupId },
      data: {
        status: hasFailed ? "FAILED" : "COMPLETED",
      },
    });
  }
}

export async function startGroupRender(groupId: string, opts?: { fresh?: boolean }) {
  const group = await prisma.multiplierGroup.findUnique({
    where: { id: groupId },
    include: {
      variations: { orderBy: { order: "asc" } },
      hooks: { orderBy: { order: "asc" } },
    },
  });

  if (!group) throw new Error("Group not found");
  if (group.variations.length === 0) throw new Error("Add at least one video variation to render");
  if (group.hooks.length === 0) throw new Error("Add at least one hook to render");

  // Resume-safe: completed outputs (and their export records) are kept — only
  // incomplete ones are replaced. Pass { fresh: true } to force a full re-render.
  let completedCombos = new Set<string>();
  if (opts?.fresh) {
    await prisma.multiplierOutput.deleteMany({ where: { groupId } });
  } else {
    await prisma.multiplierOutput.deleteMany({
      where: { groupId, status: { not: "COMPLETED" } },
    });
    const completed = await prisma.multiplierOutput.findMany({
      where: { groupId, status: "COMPLETED" },
      select: { hookId: true, variationId: true },
    });
    completedCombos = new Set(completed.map((o) => `${o.hookId}:${o.variationId}`));
  }

  // Map outputs
  if (group.mappingMode === "distribute") {
    // round-robin hooks across variations
    for (let i = 0; i < group.hooks.length; i++) {
      const hook = group.hooks[i];
      const variation = group.variations[i % group.variations.length];

      if (completedCombos.has(`${hook.id}:${variation.id}`)) continue;
      await prisma.multiplierOutput.create({
        data: {
          groupId,
          hookId: hook.id,
          variationId: variation.id,
          status: "PENDING",
        },
      });
    }
  } else {
    // each hook on each variation
    for (const hook of group.hooks) {
      for (const variation of group.variations) {
        if (completedCombos.has(`${hook.id}:${variation.id}`)) continue;
        await prisma.multiplierOutput.create({
          data: {
            groupId,
            hookId: hook.id,
            variationId: variation.id,
            status: "PENDING",
          },
        });
      }
    }
  }

  // Update status to QUEUED
  await prisma.multiplierGroup.update({
    where: { id: groupId },
    data: { status: "QUEUED", errorMessage: null },
  });

  // Run worker background loop
  triggerQueueWorker();

  return true;
}

export async function retryOutput(outputId: string) {
  const output = await prisma.multiplierOutput.update({
    where: { id: outputId },
    data: { status: "PENDING", errorMessage: null },
  });

  await prisma.multiplierGroup.update({
    where: { id: output.groupId },
    data: { status: "QUEUED" },
  });

  triggerQueueWorker();

  return output;
}

// ─── Bulk Intake (multi-video batch upload) ─────────────────────────────────

const DEFAULT_BULK_STYLE_ID = "news-lower-third";

async function addFileToBulkBatch(input: {
  jobId: string;
  file: { tempPath: string; fileName: string };
  campaignId?: string | null;
  styleId?: string | null;
  createdBy?: string | null;
  namePrefix?: string | null;
  seq?: number; // 1-based position in the naming sequence
}): Promise<string | null> {
  try {
    const name = input.namePrefix && input.seq != null
      ? `${input.namePrefix} ${String(input.seq).padStart(2, "0")}`
      : input.file.fileName.replace(/\.[^.]+$/, "") || input.file.fileName;
    const group = await prisma.multiplierGroup.create({
      data: {
        name,
        campaignId: input.campaignId || null,
        styleId: input.styleId || DEFAULT_BULK_STYLE_ID,
        mappingMode: "distribute",
        settings: {},
        createdBy: input.createdBy || null,
      },
    });

    // Moves the uploaded temp file into the variations directory
    await addVariation(group.id, input.file.tempPath, input.file.fileName);

    // The route has already received the upload, so the item starts at TRANSCRIBING
    await prisma.multiplierBatchJobItem.create({
      data: {
        jobId: input.jobId,
        fileName: input.file.fileName,
        status: "TRANSCRIBING",
        groupId: group.id,
      },
    });

    return group.id;
  } catch (err: any) {
    try { fs.unlinkSync(input.file.tempPath); } catch {}
    await prisma.multiplierBatchJobItem.create({
      data: {
        jobId: input.jobId,
        fileName: input.file.fileName,
        status: "FAILED",
        error: err?.message || String(err),
      },
    });
    return null;
  }
}

// Creates the batch shell in RECEIVING state. Files may arrive across several
// requests (see appendToBulkBatch) — processing starts only on finalizeBulkBatch.
// namePrefix enables a "PREFIX 01, 02, …" group naming sequence; the sequence
// follows arrival order (files normally arrive one request at a time, in the
// order the operator picked them).
export async function createBulkBatch(input: {
  files: { tempPath: string; fileName: string }[];
  campaignId?: string | null;
  styleId?: string | null;
  namePrefix?: string | null;
  createdBy?: string | null;
}): Promise<{ jobId: string; groupIds: string[] }> {
  ensureDirsExist();

  const namePrefix = input.namePrefix?.trim() || null;
  const job = await prisma.multiplierBatchJob.create({
    data: {
      status: "RECEIVING",
      campaignId: input.campaignId || null,
      styleId: input.styleId || null,
      namePrefix,
      createdBy: input.createdBy || null,
    },
  });

  const groupIds: string[] = [];
  for (let i = 0; i < input.files.length; i++) {
    const groupId = await addFileToBulkBatch({
      jobId: job.id,
      file: input.files[i],
      campaignId: input.campaignId,
      styleId: input.styleId,
      createdBy: input.createdBy,
      namePrefix,
      seq: i + 1,
    });
    if (groupId) groupIds.push(groupId);
  }

  return { jobId: job.id, groupIds };
}

// Appends files to an existing RECEIVING batch (one request per file keeps
// each request under proxy body-size limits, e.g. nginx client_max_body_size).
export async function appendToBulkBatch(
  jobId: string,
  files: { tempPath: string; fileName: string }[]
): Promise<string[]> {
  ensureDirsExist();

  const job = await prisma.multiplierBatchJob.findUnique({
    where: { id: jobId },
    include: { _count: { select: { items: true } } },
  });
  if (!job) throw new Error("Batch job not found");
  if (job.status !== "RECEIVING") throw new Error("Batch job is already being processed");

  const groupIds: string[] = [];
  for (let i = 0; i < files.length; i++) {
    const groupId = await addFileToBulkBatch({
      jobId,
      file: files[i],
      campaignId: job.campaignId,
      styleId: job.styleId,
      createdBy: job.createdBy,
      namePrefix: job.namePrefix,
      seq: job._count.items + i + 1,
    });
    if (groupId) groupIds.push(groupId);
  }
  return groupIds;
}

// Marks the batch ready and kicks off background processing
// (fire-and-forget, same pattern as triggerQueueWorker).
export async function finalizeBulkBatch(jobId: string): Promise<void> {
  const job = await prisma.multiplierBatchJob.findUnique({ where: { id: jobId } });
  if (!job) throw new Error("Batch job not found");
  if (job.status !== "RECEIVING") return; // already finalized — idempotent

  await prisma.multiplierBatchJob.update({
    where: { id: jobId },
    data: { status: "PROCESSING" },
  });

  processBulkBatch(jobId).catch((err) => {
    console.error(`[Multiplier Bulk Batch] Failed to trigger processing for job ${jobId}:`, err);
  });
}

let isBulkProcessing = false;

export async function processBulkBatch(jobId: string) {
  if (isBulkProcessing) {
    // CPU is scarce — process batches strictly one at a time. Retry shortly.
    setTimeout(() => {
      processBulkBatch(jobId).catch((err) => {
        console.error(`[Multiplier Bulk Batch] Error processing job ${jobId}:`, err);
      });
    }, 5000);
    return;
  }
  isBulkProcessing = true;

  try {
    const job = await prisma.multiplierBatchJob.findUnique({
      where: { id: jobId },
      include: { items: { orderBy: { createdAt: "asc" } } },
    });
    if (!job) return;

    const pendingItems = job.items.filter((i) => i.status !== "READY" && i.status !== "FAILED");

    // Pipeline: Whisper transcription is CPU-bound → strictly sequential.
    // Gemini hook generation is network-bound → small concurrent pool that
    // picks up each video as soon as its transcript lands.
    const HOOK_CONCURRENCY = 3;
    type HookTask = { itemId: string; groupId: string; fileName: string };
    const hookQueue: HookTask[] = [];
    let transcriptionDone = false;

    const hookWorker = async () => {
      while (true) {
        const task = hookQueue.shift();
        if (!task) {
          if (transcriptionDone) return;
          await new Promise((r) => setTimeout(r, 500));
          continue;
        }
        try {
          await prisma.multiplierBatchJobItem.update({
            where: { id: task.itemId },
            data: { status: "GENERATING_HOOKS" },
          });
          await generateHooks(task.groupId, 15, !!job.campaignId);
          await prisma.multiplierBatchJobItem.update({
            where: { id: task.itemId },
            data: { status: "READY" },
          });
        } catch (err: any) {
          console.error(`[Multiplier Bulk Batch] Hook generation failed for ${task.fileName}:`, err);
          await prisma.multiplierBatchJobItem.update({
            where: { id: task.itemId },
            data: { status: "FAILED", error: err?.message || String(err) },
          });
        }
      }
    };
    const hookWorkers = Array.from({ length: HOOK_CONCURRENCY }, () => hookWorker());

    for (const item of pendingItems) {
      try {
        if (!item.groupId) throw new Error("Batch item has no associated group");

        await prisma.multiplierBatchJobItem.update({
          where: { id: item.id },
          data: { status: "TRANSCRIBING", error: null },
        });
        await transcribeGroup(item.groupId);

        hookQueue.push({ itemId: item.id, groupId: item.groupId, fileName: item.fileName });
      } catch (err: any) {
        console.error(`[Multiplier Bulk Batch] Item ${item.id} (${item.fileName}) failed:`, err);
        // One bad video must not kill the batch — mark it and continue
        await prisma.multiplierBatchJobItem.update({
          where: { id: item.id },
          data: { status: "FAILED", error: err?.message || String(err) },
        });
      }
    }
    transcriptionDone = true;
    await Promise.all(hookWorkers);

    const items = await prisma.multiplierBatchJobItem.findMany({ where: { jobId } });
    const anyReady = items.some((i) => i.status === "READY");
    await prisma.multiplierBatchJob.update({
      where: { id: jobId },
      data: { status: anyReady ? "COMPLETED" : "FAILED" },
    });
  } finally {
    isBulkProcessing = false;
  }
}

export async function getBulkBatch(jobId: string) {
  return prisma.multiplierBatchJob.findUnique({
    where: { id: jobId },
    include: {
      items: {
        orderBy: { createdAt: "asc" },
        select: {
          id: true,
          fileName: true,
          status: true,
          groupId: true,
          error: true,
        },
      },
    },
  });
}

// ─── Bulk Render ─────────────────────────────────────────────────────────────

export async function bulkRenderGroups(groupIds: string[], opts?: { fresh?: boolean }): Promise<{
  queued: string[];
  skipped: { groupId: string; reason: string }[];
}> {
  const queued: string[] = [];
  const skipped: { groupId: string; reason: string }[] = [];

  for (const groupId of groupIds) {
    const group = await prisma.multiplierGroup.findUnique({
      where: { id: groupId },
      include: { _count: { select: { variations: true, hooks: true } } },
    });

    if (!group) {
      skipped.push({ groupId, reason: "Group not found" });
      continue;
    }
    if (group.status === "QUEUED" || group.status === "RENDERING") {
      skipped.push({ groupId, reason: `Group is already ${group.status.toLowerCase()}` });
      continue;
    }
    if (group._count.variations === 0) {
      skipped.push({ groupId, reason: "Add at least one video variation to render" });
      continue;
    }
    if (group._count.hooks === 0) {
      skipped.push({ groupId, reason: "Add at least one hook to render" });
      continue;
    }

    try {
      // startGroupRender triggers the queue worker internally
      await startGroupRender(groupId, opts);
      queued.push(groupId);
    } catch (err: any) {
      skipped.push({ groupId, reason: err?.message || String(err) });
    }
  }

  return { queued, skipped };
}
